### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#31]
- [x] Support for multiple tabs. Before we were detecting when the tab is reactivated, and relayed the whole history tree. It worked pretty well, except the cases when the app has background actions.
- [x] Use different monitors (wrapped into [FilterMonitor](https://github.com/zalmoxisus/redux-devtools-filter-actions)). Except the standard monitor, for now we'll add:
     - [redux-slider-monitor](https://github.com/calesce/redux-slider-monitor)
     - [redux-devtools-diff-monitor](https://github.com/whetstone/redux-devtools-diff-monitor)
     - [redux-devtools-chart-monitor](https://github.com/romseguy/redux-devtools-chart-monitor).
- [x] Ability to have multiple monitors at once (left, right and bottom).
- [x] Add buttons for opening options and devtools windows from the popup.
- [x] Support React Native, [hybrid](https://github.com/zalmoxisus/redux-devtools-extension/issues/21), [desktop](https://github.com/zalmoxisus/redux-devtools-extension/issues/13) and server side apps.

**Comment by oyeanuj** [comment]
@zalmoxisus Thank you for this extension, it is most useful! 

FWIW, I would want to add to the need for the first task in your list - support for other monitors. That is probably the only reason which makes me (and I am sure some others) still use the standard DevTools over this one.

**Comment by zalmoxisus** [comment]
Hey @oyeanuj,

Added `redux-devtools-diff-monitor` as well in `v1.0.0-beta1`. Thanks for the suggestion!

**Comment by zalmoxisus** [comment]
Released 🎉
